cmake_minimum_required(VERSION 3.30)

if(NOT IS_DIRECTORY "${NEXIUM_SOURCE_DIR}/cmake" OR NOT CHECK_DIR)
    message(FATAL_ERROR "CheckGeneratedHeaders requires NEXIUM_SOURCE_DIR and CHECK_DIR.")
endif()

function(run_cmake)
    execute_process(COMMAND "${CMAKE_COMMAND}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "${output}\n${error}")
    endif()
endfunction()

set(fixture "${CHECK_DIR}/headers")
file(MAKE_DIRECTORY "${fixture}/sources")
file(REMOVE "${fixture}/sources/Fixture.generated.h")
file(WRITE "${fixture}/sources/Fixture.h" "#pragma once\n")
file(WRITE "${fixture}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(GeneratedHeaders LANGUAGES NONE)
include("${NEXIUM_SOURCE_DIR}/cmake/NexiumTargets.cmake")
add_library(HeaderFixture INTERFACE)
nexium_add_public_headers(HeaderFixture Fixture.h Fixture.generated.h)
if(CHECK_MISSING_HEADER)
    nexium_add_public_headers(HeaderFixture Missing.h)
endif()
]=])

set(configure_args -S "${fixture}" -B "${fixture}/build"
    "-DNEXIUM_SOURCE_DIR=${NEXIUM_SOURCE_DIR}" -DCHECK_MISSING_HEADER=OFF)
run_cmake(${configure_args})
file(WRITE "${fixture}/sources/Fixture.generated.h" "#pragma once\n")
run_cmake(${configure_args})
execute_process(COMMAND "${CMAKE_COMMAND}" ${configure_args} -DCHECK_MISSING_HEADER=ON
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result STREQUAL "0" OR NOT error MATCHES "Missing.h")
    message(FATAL_ERROR "Missing ordinary headers must still fail configuration: ${output}\n${error}")
endif()

set(fixture "${CHECK_DIR}/codegen")
file(MAKE_DIRECTORY "${fixture}/sources" "${fixture}/.jrm")
file(WRITE "${fixture}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(FakeJRM LANGUAGES NONE)
if(NOT EXISTS "${PROJECT_SOURCE_DIR}/.jrm/cache.data")
    foreach(directory IN ITEMS sources tests game-example)
        file(MAKE_DIRECTORY "${PROJECT_SOURCE_DIR}/${directory}")
        foreach(extension IN ITEMS h cpp.inl)
            file(WRITE "${PROJECT_SOURCE_DIR}/${directory}/Fixture.generated.${extension}" "// generated\n")
        endforeach()
    endforeach()
    file(WRITE "${PROJECT_SOURCE_DIR}/.jrm/cache.data" "cached inputs\n")
endif()
]=])

set(codegen_args "-DJRM_EXECUTABLE=${CMAKE_COMMAND}" "-DPROJECT_ROOT=${fixture}"
    -P "${NEXIUM_SOURCE_DIR}/cmake/RunJRM.cmake")
run_cmake(${codegen_args})
foreach(directory IN ITEMS sources tests game-example)
    foreach(extension IN ITEMS h cpp.inl)
        set(generated "${fixture}/${directory}/Fixture.generated.${extension}")
        file(REMOVE "${generated}")
        run_cmake(${codegen_args})
        if(NOT EXISTS "${generated}")
            message(FATAL_ERROR "Code generation did not restore ${generated}.")
        endif()
    endforeach()
endforeach()
message(STATUS "Generated-header configuration and regeneration checks passed.")
