workflow:
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        -   if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
    - lint
    - build

variables:
    GIT_DEPTH: 0
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"

clang-format-check:
    stage: lint
    image: registry.vakon.dev/vakonteam/nexium/engine-ci:latest
    tags:
        - pull-request
    script:
        - clang-format --version
        - python3 .ci/check_clang_format.py --report-path gl-clang-format.json
    artifacts:
        reports:
            codequality: gl-clang-format.json
        when: always
        expire_in: 1 week
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

build:
    stage: build
    image: registry.vakon.dev/vakonteam/nexium/engine-ci:latest
    tags:
        - pull-request
    cache:
        key: "clang-build-cache"
        paths:
            - .ccache/
    script:
        - git submodule update --init --recursive --remote
        - cmake -S . -B build -G Ninja
            -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_C_COMPILER=clang
            -DCMAKE_CXX_COMPILER=clang++
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DCMAKE_C_COMPILER_LAUNCHER=ccache
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        - cmake --build build || (echo "BUILD FAILED — dumping ccache log:" && cat /tmp/ccache.log; exit 1)
        - ccache -s
    artifacts:
        paths:
            - build/
            - /tmp/ccache.log
        when: always
        expire_in: 1 day
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

clang-tidy-check:
    stage: build
    image: registry.vakon.dev/vakonteam/nexium/engine-ci:latest
    tags:
        - pull-request
    needs:
        - build
        - clang-format-check
    script:
        - clang-tidy --version
        - python3 .ci/check_clang_tidy.py --report-path gl-code-quality-report.json || true
    artifacts:
        reports:
            codequality: gl-code-quality-report.json
        when: always
        expire_in: 1 week
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    allow_failure: true

post-clang-tidy-comments:
    stage: build
    image: registry.vakon.dev/vakonteam/nexium/engine-ci:latest
    tags:
        - pull-request
    needs:
        - clang-tidy-check
    script:
        - python3 .ci/post_mr_comments.py --report gl-code-quality-report.json --token "$ACCESS_TOKEN"
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
            when: always
    allow_failure: true