# Pass an array of the relative paths that should be ignored.
excludedPaths:
  - .cache
  - .git
  - .idea
  - .jrm
  - .vscode
  - .venv
  - build
  - dependencies
  - .jenkins
  - data
  - docs
  - cmake
  - out

# Array of the file extensions that will be scanned through the filesystem.
parsableFileExtensions:
  - .h
  - .hpp
  - .hxx
  - .hh
  - .h++

# Show every file path while running.
showEveryIteratedFilePath: false

# Show skipped(no need update) files while running.
showSkippedFiles: false

# If true, it will always regenerate the files, regardless of whether they were modified.
alwaysDirtyCache: false

# A string will be added to the top of the generated file
insertCodeAtTheTop: "// clang-format off"

# A string will be added to the bottom of the generated file
insertCodeAtTheBottom: "// clang-format on"

# Ignore signals that are used for serialization purposes. If true, only the mehtod on(Pre/Post)[De]Serialize will be called from the top called object. If false, every class will try to use only its own on(Pre/Post)[De]Serialize method.
ignoreSerializationSignals: true