# Pass an array of the relative paths that should be ignored.
excludedPaths: 
  - .cache
  - .git
  - .idea
  - .jrm
  - .vscode
  - build
  - dependencies

# Array of the file extensions that will be scanned through the filesystem.
parsableFileExtensions: 
  - .h
  - .hpp
  - .hxx
  - .hh
  - .h++

# Show every file path while running.
showEveryIteratedFilePath: false

# Show skipped(no need update) files while running.
showSkippedFiles: false

# If true, it will always regenerate the files, regardless of whether they were modified.
alwaysDirtyCache: false

