name: clang-format

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  clang-format:
    runs-on: linux

    container:
      image: cpp-ci:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check clang-format
        id: clang-format
        env:
          GITEATOKEN: ${{ secrets.GITEATOKEN }}
        run: |
          python3 .gitea/check_clang_format.py --base develop
