= Resource system

The resource system here is straightforward.
It has a few entry points to work with it:

* `Core::GetAssetsManager()`
* `Core::GetBlueprintManager()`

Both of them are responsible for their own part of logic.

== Assets manager

It's responsible for atomic resources:

* Images: .png, .jpg, .jpeg, etc - Fonts: .ttf
* Fonts: .ttf, .otf
* 3D models: .obj, .fbx, .stl, etc
* ....

So, it represents only *one resource*.
The current goal of the Assets Manager it is to provide easy access for controlling of the resources.
Where the final user shouldn't worry about 'when to delete the resource XYZ', 'when to refresh it', 'when to save it', etc.
EVerything it is covered by the logic of `AssetsManager`.

For now, it doesn't cover the ability to give some commands to make a specific logic of the resource.
Everything that it does is just a load a resource and store it inside.
It seems to smart pointer.

The code example:

[sources,cpp]
----
#include "ResourceManager/ResourceManager.h"

auto&& am = Core::Test::GetAssetsManager();
Texture::Ptr doc = am.getTexture("/home/valerii/workspace/Nexium/data/assets/images/document.png");
std::cout << doc->getSize().width << doc->getSize().height << std::endl;
----

== Blueprint Manager

The Blueprint Manager, on the other hand, is a more complex tool.
It handles some functional stuff that can be extended, changed and scaled later.
It handles the data in the same way – you should only ask it to give you some data with a simple string; and if it exists, it will be loaded in the correct way and provided to you.

[sources,cpp]
----
#include "ResourceManager/ResourceManager.h"

auto&& bm = Core::Test::GetBlueprintManager();
auto&& blueprint = bm.findBlueprint("BaseCamera");
auto&& baseCamera = blueprint.exposeData();
----

== Blueprint - what is it?

The blueprint is a thing that describes the data, what it looks like, from what types it should be constructed, what values should be applied to it.
Under implementation (for today) is just a .json file that can describe some complex objects.
Technically, it looks like this (pseudocode):

[sources,cpp]
----
{
    "name": "SomeName",
    "type": "SomeBlueprintParserType",
    "data": {
        ...
    }
}
----

The definition of the fields is:

* *"name"* – given component name.
It will be used while spawning of the object, or for similar scenarios.
* *"type"* – the type of the parser for this blueprint(e.g. BlueprintImageParser, Blueprint3DObjectSParser).

== The info below is DEPRECATED

== Main pipeline

The main pipeline 'how it works' I will try to explain below.
In general, it's easy and it has main steps as:

=== Initial reading

At the engine xref:module-graph.adoc[init phase] it scans the filesystem with pre-registered paths to find all files with matchable extension(i.e. *.nx).
What is 'a pre-registered' path -- it's a built-in path that was registered at the engine's init stage.
For example, the main 'pre-registered' path is: `<engine_root>/data/assets`.
This object will call a function `AssetsManager::rescanFileSystem()` to find all new assets.

How to understand what asset will be scanned?
At the moment of writing this doc, it's a little bit floating question.
Because it's under active development.
But, anyway, the main asset's extension is `*.nx` -- and this logic will try to make all efforts to scan & register it inside the internal buffer.

=== Internal storing [preloading]

When it finds some file (i.g. `MyCube.nx`) it will register this asset inside internal storage with the mapped 'logical path'.
If to add more details, so it will read an asset file, write the *minimum amount of information* about scanned asset(type, name) and will put this info under the mapped name -- logical path.
Also, it will mark an asset with a status `PreLoaded` (to get this status you can call a function `ECSAsset::getLoadingStatus()`)

==== RAM\Disk storing & loading

You should keep in your mind that it has different stages of loading of your assets' main information.
It can't just totally load all assets and store it inside the RAM.
It's impossible due to the huge number of data( models, textures, etc).
So, it will load only assets that you really need & want to use NOW (In the nearest future I'll add a new system\logic to put some priority or time-gap when to unload an asset).
But you should know only one rule: _you are using the asset `X` \-> it stores its data in RAM.
If you don't use (i.e. delete from a scene) \-> it will be immediately unloading from the RAM.
And after a future\new request to this asset `X` it will be read again *main data* from the disk_

Now, main 'stages' of your assets you can read at the enum class `ECSAsset::Status`.
Briefly, it has the main point:

. *NotLoaded* -- Absolutely not loaded.
Asset's type is undefined
. *PreLoaded* -- Loaded only the main information: type & ID & name
. *Loaded* -- Full asset's data is loaded (corresponding to asset's type)
. *PreLoadingError* -- Error while preloading data
. *LoadingError* -- Error while loading of the main data

==== Regarding 'logical path'

To be honest with you, the logical path is just a string, but it represents the path to this asset and it should be unique.
To don't worry about the uniqueness of the assets through the engine, we can delegate this work to the OS filesystem.

==== Example

Let's check a small example.
We have the default configuration of the engine.
Only one path(default one) has registered inside the `AssetsManager` is `<engine_root>/data/assets`.
Also, we have only one asset `MyCube.nx`

. At the engine's init stage it will call a function `AssetsManager::rescanFileSystem()`
. After that, it will scan the folder recursively and will find our asset `MyCube.nx` inside the folder: `<engine_root>/data/assets/3d-models/MyCube.nx`
. The `AssetsManager` will register this asset under the logical path `3d-models/MyCube` -- *it will the unique identifier of your asset*.

== Extra path registration

As far as you know, it has only one pre-registered path: `<engine_root>/data/assets`
But, if you need you can add\register more paths if you need it using `AssetsManager::registerNewAssetPath(your_path)`.

== Getting loaded assets

At the moment of writing this doc, to retrieve some assets, you need to get the object of the described class and call a function `Core::AssetsManager::getAsset(logical_path)`.
It's the best way to get what you need.

== Real code example

Let's see at the main pipeline behind all extra information.

[source,cpp]
----
// First scan at the engine's initialization. You shouldn't do that directly!
gGameInstance->assets.rescanFileSystem();
// or
// GetAssetsManager().rescanFileSystem()

// For example we have only one asset: data/assets/3d-models/MyCube.nx
// The rescanFileSystem() found this asset and put into internal storage.
// It wrote the meta data of this asset:
//    type: StaticMeshBundle
//    name: MyFirstCube
//    logicPath: 3d-models/MyCube.nx
//    pathToSource: <engine_root>/data/assets/3d-models/MyCube.nx
//    status: PreLoaded

// Let's try to get this asset & make a full load
NXAsset cube = GetAssetsManager().getAsset("3d-models/MyCube.nx"_atom);
// At the moment of getting this assets, the subsystem sees that you want to get all data.
// So, it reads all really main data about it from the corresponsing file, and loads it
// just at this line. So, at the next line you can use it as you want!

if (cube)
{
    cout << cube.getLoadingStatus() == ECSAsset::StatusLoaded; // true
}
----

