#!/bin/sh
# Nexium-specific values consumed by the shared scripts/ci/gitea runners.
# This file defines data only; source it from a workflow step or runner.

CI_JOBS=4

CI_GCC_COMPILER=gcc
CI_GCC_BUILD_TYPE=Debug
CI_GCC_CHECKOUT_PATH=cache/gcc/debug
CI_GCC_PROJECT_DIR=/workspace/Vakon/Nexium/cache/gcc/debug
CI_GCC_BUILD_DIR=/cache/build/gcc/debug
CI_GCC_CCACHE_DIR=/ccache/gcc/debug

CI_CLANG_COMPILER=clang
CI_CLANG_BUILD_TYPE=Debug
CI_CLANG_CHECKOUT_PATH=cache/clang/debug
CI_CLANG_PROJECT_DIR=/workspace/Vakon/Nexium/cache/clang/debug
CI_CLANG_BUILD_DIR=/cache/build/clang/debug
CI_CLANG_CCACHE_DIR=/ccache/clang/debug

CI_COVERAGE_COMPILER=gcc
CI_COVERAGE_BUILD_TYPE=Debug
CI_COVERAGE_BUILD_DIR=/cache/build/gcc/coverage
CI_COVERAGE_CCACHE_DIR=/ccache/gcc/coverage

CI_BOOTSTRAP_SUBMODULES='dependencies/JustReflectMe dependencies/Utils'
CI_CACHED_SUBMODULES='.agents/Agents dependencies/assimp dependencies/freetype dependencies/glfw dependencies/spdlog scripts'

CI_CMAKE_GENERATOR=Ninja
CI_DISABLE_TESTS=OFF
CI_DISABLE_BENCHMARKS=ON
CI_ENABLE_3D_MODULE=OFF
CI_VERIFY_INTERFACE_HEADER_SETS=ON
CI_ENABLE_LAYER_CHECKS=ON
CI_ENABLE_CODE_COVERAGE=ON

CI_GCC_CMAKE_OPTIONS='-DNEXIUM_DISABLE_TESTS=OFF -DNEXIUM_DISABLE_BENCHMARKS=ON -DNEXIUM_ENABLE_3D_MODULE=OFF -DNEXIUM_VERIFY_INTERFACE_HEADER_SETS=ON -DNEXIUM_ENABLE_LAYER_CHECKS=ON'
CI_CLANG_CMAKE_OPTIONS='-DNEXIUM_DISABLE_TESTS=OFF -DNEXIUM_DISABLE_BENCHMARKS=ON -DNEXIUM_ENABLE_3D_MODULE=OFF -DNEXIUM_VERIFY_INTERFACE_HEADER_SETS=ON -DNEXIUM_ENABLE_LAYER_CHECKS=ON'
CI_COVERAGE_CMAKE_OPTIONS='-DNEXIUM_DISABLE_TESTS=OFF -DNEXIUM_DISABLE_BENCHMARKS=ON -DNEXIUM_ENABLE_CODE_COVERAGE=ON -DNEXIUM_ENABLE_3D_MODULE=OFF -DNEXIUM_VERIFY_INTERFACE_HEADER_SETS=OFF -DNEXIUM_ENABLE_LAYER_CHECKS=OFF'

CI_TEST_TARGET=Nexium_Tests
CI_TEST_EXECUTABLE=bin/Nexium_Tests
CI_GAME_TARGET=TemplateGame
CI_GAME_EXECUTABLE=bin/TemplateGame
CI_COVERAGE_TARGET=Nexium_Coverage
CI_VALGRIND_SUPPRESSIONS=valgrind.supp
CI_GAME_WINDOW_CACHE=data/cache/RootWindow.json
CI_GAME_HEADLESS_ENVIRONMENT=NEXIUM_HEADLESS_GL=1
CI_GAME_TIMEOUT_SECONDS=5
CI_GAME_SCREENSHOT_NAME=template-game-ui.png

CI_CHANGED_FILE_EXCLUDES='dependencies/ docs/ cmake/ data/'
CI_COPYRIGHT_START_YEAR=2018
CI_COPYRIGHT_HOLDER='Valerii Koniushenko'
CI_COPYRIGHT_LICENSE_LINE_1='//'
CI_COPYRIGHT_LICENSE_LINE_2='// Licensed under the Apache License, Version 2.0 (the "License");'
CI_COPYRIGHT_LICENSE_LINE_3='// you may not use this file except in compliance with the License.'
CI_COPYRIGHT_LICENSE_LINE_4='// You may obtain a copy of the License at'
CI_COPYRIGHT_LICENSE_LINE_5='//'
CI_COPYRIGHT_LICENSE_LINE_6='//     http://www.apache.org/licenses/LICENSE-2.0'
